# Generated by Django 5.2.11 on 2026-02-27 13:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import taxonomy.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('path', taxonomy.fields.LTreeField(blank=True, default='')),
                ('rank', models.CharField(choices=[('kingdom', 'Kingdom'), ('phylum', 'Phylum'), ('class', 'Class'), ('order', 'Order'), ('family', 'Family'), ('genus', 'Genus'), ('species', 'Species')], db_index=True, max_length=50)),
                ('scientific_name', models.CharField(db_index=True, max_length=255)),
                ('authorship', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('synonym', 'Synonym'), ('provisionally accepted', 'Provisionally Accepted')], default='accepted', max_length=50)),
                ('extinct', models.BooleanField(default=False)),
                ('kingdom', models.CharField(blank=True, default='', max_length=255)),
                ('phylum', models.CharField(blank=True, default='', max_length=255)),
                ('klass', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.CharField(blank=True, default='', max_length=255)),
                ('family', models.CharField(blank=True, default='', max_length=255)),
                ('genus', models.CharField(blank=True, default='', max_length=255)),
                ('species_count', models.IntegerField(default=0)),
                ('iucn_status', models.CharField(blank=True, choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct'), ('DD', 'Data Deficient'), ('NE', 'Not Evaluated')], default='', max_length=2)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomy.taxon')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('license', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='taxonomy.taxon')),
            ],
        ),
        migrations.CreateModel(
            name='VernacularName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('language', models.CharField(max_length=3)),
                ('is_preferred', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=50)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vernacular_names', to='taxonomy.taxon')),
            ],
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=django.contrib.postgres.indexes.GistIndex(fields=['path'], name='taxon_path_gist'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='taxon_search_gin'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['scientific_name'], name='taxon_sciname_idx'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['rank'], name='taxon_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['parent'], name='taxon_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='vernacularname',
            index=models.Index(fields=['name'], name='vernacular_name_idx'),
        ),
        migrations.AddIndex(
            model_name='vernacularname',
            index=models.Index(fields=['language'], name='vernacular_lang_idx'),
        ),
    ]
