# Generated by Django 5.2.11 on 2026-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_trigram_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='authorship',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='scientific_name',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
